language: android
install: true
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_977df3c49344_key -iv $encrypted_977df3c49344_iv -in $TRAVIS_BUILD_DIR/secring.gpg.enc -out $TRAVIS_BUILD_DIR/secring.gpg.enc -d

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -Psigning.keyId=$signing_key_id -Psigning.password=$signing_password -Psigning.secretKeyRingFile=$TRAVIS_BUILD_DIR/secring.gpg.enc
    on:
      branch: master

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
