language: java
install: true
sudo: false

jdk:
  - oraclejdk7

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_script:
  - chmod +x gradlew

script:
  - ./gradlew common:publishToMavenLocal
  - ./gradlew decorator:publishToMavenLocal
  - ./gradlew no-op:publishToMavenLocal
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)

before_deploy:
  - chmod -R +x tools

deploy:
  - provider: script
    script: ./.buildscript/deploy_snapshot.sh
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    secure: RJYBoHJ7p3TCHqdWcsTj1Wq2Et97l9jPj3khOlprH/U+LO21/71qCH3oWD3o41M0CaNfyG1K/AlLcSVWN/2btvfcs48aY9T6kNWzZF2ku4PkzhAQolzi/Uxlpc+tX72hDYE2Q3nt1GgWDRI5nfYPOHYxt54wDswmJpjTNq7Y8DQ0pUhfFaOVIB5cW2ozLZq+x3hzBYdACp0b7eR3AG5jdexXKMMZy/K+JCuE46apzn8OZTqpUNaMjiy8l3y180tp60fbyHAidHPdz1fZ/b/m2//eLWXTU9TW9xxHVMGQrdB6kGw4ca3iUX0rDgPLtBmqUa9IZTSy+N/myelUXKaHd2bfbPXF8JgfVQtakjn+LdsIWHAqH4X+enPxL1McsuhAB3hvgViRVfnPdbMJHuBTLk+JHJNnUKPtkdS9aE+OCRSVI+vZqvFnLU23Xe3mJwa2IaWK3OsW0ayokxz8URkbDsl1Si71oBNQGxzzb1mQMa+3uGtrtAg2rnFKeov4oPT5Ka1jedc+/iWM00cv0FmjeN29VHXbvx/gW3EeLAySoWYQ76w1hK04qSu2u5A/qT4EoxNfbJNIE2Owmk+6rSZ0wUbhQlbLB8oYoZtqbfWRrfT3Ho+m7Wa2onMarAlkgalIQHOhgmBzwLaD+izLCP0HS5rZ7CjPA/UQq2TMdY6ifFE=
    secure: MXjlZEcY7NAWpGBfvXsFCAa/556aCAjnR/W23TxywgJz+pbzGV7svRrTXICRP5gl63/A8olNxOTCXtHAnp/gr3oPhhQz2X56J5lLwpgksXQxOasbKJqO0z46iNrF4vw3Zd+EV2IvWgCubXe+o/HAsRwt1TCYYL8vobaj1sLwIDvVDsqy0yYlzoBLRnHzKxMvm2qsehMaS9wFlanVgXWIpCJzGzT+y4oacQH2fWliIpN+VGn5XfqmgPLvcdOyQbRbsbsF+M7rdxwlsAn7hAgveegPDWOa/Ufq3OqvWnWY70QKzLS3pO2iraI/gBGa7SGcwYgHbqLWftakDBDYtqiM/HfDbbZ65cT81utLYVgQfVj4h6QdrT1JBq5AMyZIwpddZgieh+F2WksICZt8ej5ID1IAjh7BakVPZ5132g429TN+QMo0jQLoxOFh5fZwxL2ot40cWItI+H4k2UA+T8sj2nY+KLFmO3UVeeu4fwVaKN3ml2nLfIyutfyjieRahjnChpu1WLY/QJFp+qH2UBcw+HAiWzUQwUVTD8/7KN6VPO1V0Rc+UvX3Jvqw7ITHRf29DuypEs6U9LAYnCMju96C4iN2UpX0TUV2C4p5kAnujyNVRlEkrHpJtPRWTs7YWIJmFajxmXOxyQilU+Dev6+rjnmGzTpJQAczQF6sCt9ObRw=

branches:
  only:
    - master
    - /^release.*$/
