language: android
install: true
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_977df3c49344_key -iv $encrypted_977df3c49344_iv -in secring.gpg.enc -out $TRAVIS_BUILD_DIR/secring.gpg -d

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew build ciPerformRelease

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
